/**
 * Open Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InternationalizedString } from './internationalizedString';

export interface CreateUserDTO {
  title: InternationalizedString;
  firstName: InternationalizedString;
  lastName: InternationalizedString;
  dateOfBirth: Date;
  email: string;
  password: string;
  termsOfService: Array<string>;
}
