/**
 * Open Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { AuthSignInDTO } from '../model/authSignInDTO';
import { AuthToken } from '../model/authToken';
import { UserDTO } from '../model/userDTO';

import { Configuration } from '../configuration';

export interface AuthServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  authControllerCurrentUser(extraHttpRequestParams?: any): Observable<UserDTO>;

  /**
   * Sign in
   *
   * @param body
   */
  authControllerLogin(body: AuthSignInDTO, extraHttpRequestParams?: any): Observable<AuthToken>;
}
