/**
 * Open Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { CreateEventDTO } from '../model/createEventDTO';
import { Event } from '../model/event';
import { SetTagsDTO } from '../model/setTagsDTO';

import { Configuration } from '../configuration';

export interface EventServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Create an event
   *
   * @param body
   */
  eventControllerCreateEvent(body: CreateEventDTO, extraHttpRequestParams?: any): Observable<Event>;

  /**
   * List all events
   *
   */
  eventControllerFindAll(extraHttpRequestParams?: any): Observable<Array<Event>>;

  /**
   * List tags of an event
   *
   * @param id
   */
  eventControllerFindAllTags(id: string, extraHttpRequestParams?: any): Observable<Array<string>>;

  /**
   * Find an event from ID
   *
   * @param id
   */
  eventControllerFindById(id: string, extraHttpRequestParams?: any): Observable<Event>;

  /**
   * Set tags of an event
   *
   * @param body
   * @param id
   */
  eventControllerSetTags(
    body: SetTagsDTO,
    id: string,
    extraHttpRequestParams?: any
  ): Observable<Array<string>>;
}
