/**
 * Open Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { AddMemberDTO } from '../model/addMemberDTO';
import { CreateOrganizationDTO } from '../model/createOrganizationDTO';
import { Organization } from '../model/organization';
import { OrganizationMember } from '../model/organizationMember';

import { Configuration } from '../configuration';

export interface OrganizationServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Add a user to an organization
   *
   * @param body
   * @param id
   */
  organizationControllerAddMember(
    body: AddMemberDTO,
    id: string,
    extraHttpRequestParams?: any
  ): Observable<Array<OrganizationMember>>;

  /**
   * Create an organization
   *
   * @param body
   */
  organizationControllerCreateOrganization(
    body: CreateOrganizationDTO,
    extraHttpRequestParams?: any
  ): Observable<Organization>;

  /**
   * List all organizations
   *
   */
  organizationControllerFindAll(extraHttpRequestParams?: any): Observable<Array<Organization>>;

  /**
   * List all members in an organization
   *
   * @param id
   */
  organizationControllerGetMembers(
    id: string,
    extraHttpRequestParams?: any
  ): Observable<Array<OrganizationMember>>;

  /**
   * Remove a user from an organization
   *
   * @param id
   * @param memberid
   */
  organizationControllerRemoveMember(
    id: string,
    memberid: string,
    extraHttpRequestParams?: any
  ): Observable<Array<OrganizationMember>>;
}
