/**
 * Open Registration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { CreateUserDTO } from '../model/createUserDTO';
import { UserDTO } from '../model/userDTO';

import { Configuration } from '../configuration';

export interface UserServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Create a user
   *
   * @param body
   */
  userControllerCreate(body: CreateUserDTO, extraHttpRequestParams?: any): Observable<UserDTO>;

  /**
   * List all users
   *
   */
  userControllerFindAll(extraHttpRequestParams?: any): Observable<Array<UserDTO>>;

  /**
   * Find a user from ID
   *
   * @param id
   */
  userControllerFindById(id: string, extraHttpRequestParams?: any): Observable<UserDTO>;
}
