name: Build and Test
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: |
          yarn
      - name: Test
        run: |
          yarn test:ci
      - name: Build
        if: github.event_name == 'pull_request'
        run: |
          yarn build --prod
      - name: Push Build to Development
        uses: amondnet/vercel-action@v19.0.1+1
        id: vercel-action-staging
        if: github.event_name == 'pull_request'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECTID }}
      - name: Push Build to Staging
        uses: amondnet/vercel-action@v19.0.1+1
        id: vercel-action-production
        if: github.event_name == 'push'
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECTID }}
